language: php

dist: xenial

services:
  - memcached
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: PREFER_LOWEST=1 DB=sqlite DB_URL='sqlite:///:memory:'

before_install:
  - echo cakephp version && tail -1 VERSION.txt

  - |
      phpenv config-rm xdebug.ini
      echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - sudo locale-gen da_DK.UTF-8

install:
  - |
      if [[ $PREFER_LOWEST == 1 ]]; then
        composer update --prefer-lowest --prefer-stable --no-interaction
      else
        composer install --no-interaction
      fi

script:
  - vendor/bin/phpunit

notifications:
  email: false
