language: php

dist: xenial

services:
  - memcached
  - redis-server

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: PREFER_LOWEST=1 DB=sqlite db_dsn='sqlite:///:memory:'

before_install:
  - echo cakephp version && tail -1 VERSION.txt
  - phpenv config-rm xdebug.ini

  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - echo "yes" | pecl install apcu-4.0.11 || true

  - sudo locale-gen da_DK
  - sudo locale-gen de_DE

before_script:
  - composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction
  - composer require --dev dereuromark/composer-prefer-lowest

script:
  - vendor/bin/phpunit
  - vendor/bin/validate-prefer-lowest

notifications:
  email: false
